id: PA6E00942
initial_creation_type: ocr
source_metadata:
  volumes:
    a39d3ad546254175b8cf04b06a53d9f2:
      base_file: v013.txt
      image_group_id: I1PD95858
      title: མཆན་ཁུང་གི་སྦྱོར་བ།
      total_pages: 2043
      volume_number: 13
